<a href="https://colab.research.google.com/github/spshreya/dataAnalytics/blob/main/revision_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY REVISION

In [51]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([0, 0.5, 1, 1.5, 2])
type(a)

numpy.ndarray

In [3]:
a.dtype

dtype('int64')

In [4]:
a = np.array([1,2,3,4], dtype='int8')
a.dtype

dtype('int8')

In [5]:
a[0], a[1]

(1, 2)

In [6]:
b[0], b[2], b[-1]  

(0.0, 1.0, 2.0)

In [7]:
b[[0,2,-1]] #multi indexing which can not be found in lists but np arrays


array([0., 1., 2.])

In [8]:
a[1:]

array([2, 3, 4], dtype=int8)

In [9]:
a[1:-1]

array([2, 3], dtype=int8)

In [10]:
a[::2]   #[x::y] prints yth element from the list starting from x

array([1, 3], dtype=int8)

In [11]:
#multidimensional array
aa = np.array([
               [1,2,3],
               [4,5,6]
], dtype='int8')
aa.dtype

dtype('int8')

In [12]:
print('shape =',aa.shape)
print('dimensions=', aa.ndim)
print('size=', aa.size)

shape = (2, 3)
dimensions= 2
size= 6


In [13]:
#a dimension further
bb = np.array([
               [
                [1,2,3],
                [4,5,6]
               ],
               [
                [6,7,8],
                [9,10,11]
               ]
], dtype='float64')
bb

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]])

In [14]:
print('shape =',bb.shape)
print('dimensions=', bb.ndim)
print('size=', bb.size)

shape = (2, 2, 3)
dimensions= 3
size= 12


In [15]:
#in case of mismatched rows - notice the difference
c = np.array([
              [
               [1,2,3],
               [4,5,6]
              ],
              [
               [7,8,9]
              ]
])
c.dtype

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


dtype('O')

In [16]:
print('shape =',c.shape)
print('dimensions=', c.ndim)
print('size=', c.size)

shape = (2,)
dimensions= 1
size= 2


In [17]:
#slicing nad indexing square matrix
a= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [18]:
a[1][0]

4

In [19]:
#or 
a[1, 0]

4

In [20]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a[:, :2]    #a[d1, d2, d3, d4]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [22]:
a[1] = np.array([2,2,2])
a

array([[1, 2, 3],
       [2, 2, 2],
       [7, 8, 9]])

In [23]:
#or we can just leave it to numpy
a[2]= 10
a

array([[ 1,  2,  3],
       [ 2,  2,  2],
       [10, 10, 10]])

In [24]:
# STATS

a = np.array([1,2,3,4], dtype='int8')

In [25]:
print(a.max(), a.min(), a.sum(), a.mean(), a.std(), a.var())

4 1 10 2.5 1.118033988749895 1.25


In [28]:
a= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(a.sum(), a.sum(axis=0), a.sum(axis=1))

45 [12 15 18] [ 6 15 24]


In [30]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
#broadcasting and vectorized operations
a = np.arange(4)
a

array([0, 1, 2, 3])

In [33]:
b = np.arange(2,20,2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
a + 10

array([10, 11, 12, 13])

In [36]:
b * 10

array([ 20,  40,  60,  80, 100, 120, 140, 160, 180])

In [37]:
l = [1,2,3,4]
l + 10   #won't work

TypeError: ignored

In [38]:
# Boolean arrays
a

array([0, 1, 2, 3])

In [39]:
a[[0,-1]]

array([0, 3])

In [42]:
a[[True, False, False, True]]

array([0, 3])

In [43]:
a >= 2

array([False, False,  True,  True])

In [44]:
a[a >= 2]

array([2, 3])

In [47]:
a[a >= a.mean()]

array([2, 3])

In [48]:
a[~(a >= a.mean())]

array([0, 1])

In [50]:
a[(a==0) | (a==1)]

array([0, 1])

In [53]:
#linear algebra
a = np.array([
              [1,2,3],
              [4,4,4],
              [5,6,7]
])

b = np.array([
              [10,20],
              [50,60],
              [70,8]
])

In [54]:
a.dot(b)    #dot product

array([[320, 164],
       [520, 352],
       [840, 516]])

In [55]:
a @ b   #dot product

array([[320, 164],
       [520, 352],
       [840, 516]])

In [56]:
b.T    #transpose

array([[10, 50, 70],
       [20, 60,  8]])

In [59]:
b.T @ a

array([[560, 640, 720],
       [300, 328, 356]])

In [63]:
# sizes
import sys
sys.getsizeof(1)     #unnecessarily large

28

In [64]:
sys.getsizeof(10**100)     #longs even larger

72

In [65]:
np.dtype(int).itemsize         #comparatively smaller

8

In [66]:
np.dtype(np.int8).itemsize       #very small

1

In [67]:
np.dtype(float).itemsize  

8

In [68]:
sys.getsizeof([1])       #even lists are larger

80

In [69]:
np.array([1]).nbytes

8

In [77]:
#time performance

l = list(range(1000))
a = np.arange(1000)

In [78]:
%time sum([x**2 for x in l])

CPU times: user 470 µs, sys: 0 ns, total: 470 µs
Wall time: 478 µs


332833500

In [79]:
%time sum(a**2)

CPU times: user 300 µs, sys: 0 ns, total: 300 µs
Wall time: 268 µs


332833500

In [ ]:
#also see reshape, linspace, zeros, ones, empty, identity, eye